# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsher < Formula
  desc "CLI tool describing ECS resources like kubectl written in Go"
  homepage "https://github.com/Mic-U/ecsher"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.13.0/ecsher_0.13.0_Darwin_x86_64.tar.gz"
      sha256 "16c101b2eb49f47345cd5e8f3598d13373ed53a5c3a370878e07386320c75897"

      def install
        bin.install "ecsher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.13.0/ecsher_0.13.0_Darwin_arm64.tar.gz"
      sha256 "f8e6734a5f5f47b16af15738cda2cd03ba8d048ce7acab363318e9f9ab7b579f"

      def install
        bin.install "ecsher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.13.0/ecsher_0.13.0_Linux_x86_64.tar.gz"
      sha256 "85631d7e28956bf1b6e59fa621936612f5bbbaeed18ae419ae5e452faf9c654c"

      def install
        bin.install "ecsher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.13.0/ecsher_0.13.0_Linux_arm64.tar.gz"
      sha256 "c2df211121e9919038868aa520e33dc1c9b4e467da433beb5e381ed21e3f7791"

      def install
        bin.install "ecsher"
      end
    end
  end
end
