# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsher < Formula
  desc "CLI tool describing ECS resources like kubectl written in Go"
  homepage "https://github.com/Mic-U/ecsher"
  version "0.15.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.15.1/ecsher_Darwin_x86_64.tar.gz"
      sha256 "2cb58c56b977090a266d39b0ad3e9ff31225c53696c0b83405af3d86aa0cc0a3"

      def install
        bin.install "ecsher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.15.1/ecsher_Darwin_arm64.tar.gz"
      sha256 "94af55e317773f5583c6972ddc1dd6c3736ff57a1c100633c5d016e94effd069"

      def install
        bin.install "ecsher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.15.1/ecsher_Linux_x86_64.tar.gz"
      sha256 "f5778c514c7c8fed8e332c1988f6b9dc3e30889b6e706342c66b27188102b2ae"

      def install
        bin.install "ecsher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mic-U/ecsher/releases/download/v0.15.1/ecsher_Linux_arm64.tar.gz"
      sha256 "67d3bb19d34fd5cfb392211d7948ee34ee0d53996739be68fe5005f39b6e5077"

      def install
        bin.install "ecsher"
      end
    end
  end
end
